/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  ComponentA as ComponentA
} from './components/component-a/component-a';

declare global {
  interface HTMLComponentAElement extends ComponentA, HTMLElement {
  }
  var HTMLComponentAElement: {
    prototype: HTMLComponentAElement;
    new (): HTMLComponentAElement;
  };
  interface HTMLElementTagNameMap {
    "component-a": HTMLComponentAElement;
  }
  interface ElementTagNameMap {
    "component-a": HTMLComponentAElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "component-a": JSXElements.ComponentAAttributes;
    }
  }
  namespace JSXElements {
    export interface ComponentAAttributes extends HTMLAttributes {
      
        first?: string,
        last?: string
    }
  }
}

