/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@stephenwf/component-a';


import {
  ComponentB as ComponentB
} from './components/component-b/component-b';

declare global {
  interface HTMLComponentBElement extends ComponentB, HTMLElement {
  }
  var HTMLComponentBElement: {
    prototype: HTMLComponentBElement;
    new (): HTMLComponentBElement;
  };
  interface HTMLElementTagNameMap {
    "component-b": HTMLComponentBElement;
  }
  interface ElementTagNameMap {
    "component-b": HTMLComponentBElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "component-b": JSXElements.ComponentBAttributes;
    }
  }
  namespace JSXElements {
    export interface ComponentBAttributes extends HTMLAttributes {
      
        first?: string,
        last?: string
    }
  }
}

